#!/bin/bash
export KBUILD_BUILD_USER=NexusG4x
export KBUILD_BUILD_HOST=Plume
echo $KBUILD_BUILD_USER
echo $KBUILD_BUILD_HOST
echo -e "done?"
sleep 2s

make CC=clang ARCH=arm64 O=out RMX1941_defconfig
make CC=clang ARCH=arm64 O=out -j16 \
        HEADER_ARCH=arm64 \
        SUBARCH=arm64 \
        CXX=c++ \
    AR=llvm-ar \
    NM=llvm-nm \
    OBJDUMP=llvm-objdump \
    STRIP=llvm-strip \
      	CROSS_COMPILE=aarch64-linux-gnu- \
	CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
        CLANG_TRIPLE=aarch64-linux-gnu-
